# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('writer', models.CharField(max_length=10)),
                ('contents', models.CharField(max_length=1000)),
                ('comments', models.CharField(max_length=10)),
                ('postNum', models.IntegerField()),
            ],
        ),
    ]
