# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postNum', models.IntegerField()),
                ('commentNum', models.IntegerField()),
                ('writer', models.CharField(max_length=10)),
                ('contents', models.CharField(max_length=1000)),
            ],
        ),
    ]
