# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_posts', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='postNum',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='list_posts.Post'),
            preserve_default=False,
        ),
    ]
