# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_posts', '0003_auto_20160116_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='postNum',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
