# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_posts', '0004_auto_20160116_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postNum',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
